name: Deploy PWA – Dev → Prod bucket

on:
  push:
    branches: [dev]

permissions:
  id-token: write       
  contents: read        

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}             
      CF_DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION }}  

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci --prefer-offline --no-audit

      - name: Build (Vite)
        run: npm run build

      - name: Assume AWS role via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3 (overwrites prod)
        run: |
          aws s3 sync dist/ s3://$AWS_BUCKET \
            --delete \
            --cache-control public,max-age=31536000,immutable

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CF_DISTRIBUTION \
            --paths '/*'
